name: Build Workflow
on: [push]

jobs:
  build:
    name: buildhack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: make the module distribution tarball
        run: |
          perl Makefile.PL
          make
          make manifest
          make dist
  upload:
    name: uploadhack
    runs-on: ubuntu-latest
    steps:
      - name: upload tarball from build
        uses: actions/upload-artifact@v1
        with:
          name: tarball
          path: tarball/*.tar.gz
